# Generated by Django 3.1.6 on 2021-02-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210206_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=8, verbose_name='주문상태'),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
