# Generated by Django 3.1.6 on 2021-02-06 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210206_0444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '주문', 'verbose_name_plural': '주문'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={},
        ),
    ]
