# Generated by Django 3.1.6 on 2021-02-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210206_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='결제일'),
        ),
    ]
