# Generated by Django 3.1.6 on 2021-02-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid_date',
        ),
    ]
