# Generated by Django 3.0.5 on 2021-02-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='제조사')),
                ('stock', models.IntegerField(verbose_name='재고수량')),
                ('unit_price', models.IntegerField(verbose_name='단가')),
                ('expiration_date', models.DateTimeField(auto_now_add=True, verbose_name='유통기한')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'products',
            },
        ),
    ]
